// <auto-generated />
namespace Blogcatch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InsertSqlIntoWidget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertSqlIntoWidget));
        
        string IMigrationMetadata.Id
        {
            get { return "201708312016312_InsertSqlIntoWidget"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
